spring:
  application:
    name: VotingSystem

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.posGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
